Add Snakemake workflow for Zooma mapping migration in codon (#27)
* add Snakemake wf rule definitions to replace updateExperimentMetadata.sh

* add comment

* Add docstring to get_outptus()

* Create rule check_zooma

* Start rule remove_aux_files

* Define rule 'all'

* restructure workflow [skip ci]

* edit rules

* add get_working_dir function

* add content to shell in rule run_condense_sdrf

* Update get_accessions

* Edit get_accessions

* Add param to parse

* Add conditionals to determine working dir

* Renamed workdir var for consistency

* Add sourcing of script with applyAllFixesForExperiment

* Export applyAllFixesForExperiment

* Syntax correction

* Define inputs, output, and shell for apply_fixes rule

* Supply variables for apply_fixes rule

* few edits to Snakefile [skip ci]

* add popd

* further edits to Snakefile rules

* Python edits

* add rule split_zooma_mapping_report

* add rule copy_reports_to_targetDir

* finalise rules of main workflow

* correct bad substitution error

* correct `name 'acc' is not defined`

* add function to return attempt number

* correct typo

* remove f-string to enable expand; delete comma; add check for  {params.split_report_files}

* add def get_split_report_files(wildcards)

* correct typo in rule all input

* move input to params

* add quotes to try solving `NameError: The name 'http_code' is unknown in this context.`

* fix conditional logic in rule check_zooma

* braces not used for variable access have to be escaped by repeating them

* add lambda wildcard to solve TypeError: get_attempt() missing 1 required positional argument: 'attempt'

* mv attempt_number to 'resources:'

* braces not used for variable access have to be escaped by repeating them

* braces not used for variable access have to be escaped by repeating them

* $targetDir to ${{targetDir}}

* add param notifEmail

* add config['previousRunDate'] to snakemake workflow

* braces not used for variable access have to be escaped by repeating them

* braces not used for variable access have to be escaped by repeating them

* add localrule list; correct syntax errors;  enable wet run

* correct path to get_experiment_type_from_xml.pl

* provision IDF path explicitly to condese_sdrf.pl; replace $mode with {params.mode}

* enable AllFixesForExperiment via new env with conda package atlas-bash-util

* add ebi-gene-expression-group to channels

* fix logic in rule run_condense_sdrf

* fix zooma mapping report filename

* add condense_sdrf.pl to /bin/

* fix path to zooma exclusions file

* add /zooma-mappings-wf/bin/  to condense_sdrf.pl path

* add -x {params.zooma_exclusions} for non-baseline experiments

* eliminate local copy of condense_sdrf.pl
fix name of split_report_files

* make output temp for rule copy_reports_to_targetDir;
remove backup of old condensed

* last 2 rules should execute once

* enable email notification; correct indent

* correct error 'Missing input files for rule all'

* move to f-string

* add few echos for debugging

* get symbolic link from previous_run dir

* use mamba to handle conda installs

* add atlas_ftp to config; export vars for single_cell_condensed_sdrf.sh

* add -z  zoomaExclusions

* rm cd $SCRIPTDIR

* add perl to dependencies

* add output to rule run_condense_sdrf

* correct syntax error

* add lambda wildcards to request config_xml input

* add mode-based directory stack

* export path to avoid failure in checkExecutableInPath()

* change targetDir for mode = "single_cell"

* add linting of Snakefile with snakemake-github-action@v1

* correct linting path; add `%H:%M` to date_time to enable running the workflow more than once in a day

* define timestamp only once in the workflow

* add input param get_split_report_files to funcs

* fix bug: atlas -> {params.mode};
edit linting (snakemake-github-action@v1)

* add missing params to snakemake config (for linting)

* rm debugging comments

* define 'load' as additional resource that shall constrain the scheduling for zooma jobs

* set minimum Snakemake version

* add load_zooma_jobs config to linting

* move python functions into a common module at rules/common.smk

* add conda env to all rules to meet CI lint requirements

* edit base channels and dependency; string formatting

* attempt to combine regex with f-string

* revert to initial wildcard

* aim to correct linting error

* combine regular expression and f-string

* apply code formatter

* revert changes introduced by the automatic code formatter for split_zooma_mapping_report.sh

* code formatting

* target dest is not ATLAS_FTP anymore

* change logs dirname

* add condig parameter to keep backup of SDRF file

* fix typo

* correct conditional if

* correct dest path in agreement with curators;
rename mode "atlas" to "bulk"

* fix default MODE=${MODE:-"bulk"}

* add missing quote

* add config params to linting; relocate set +e

* attempt sending notification email only if `notifEmail=true`

* add comment on minimal input required for the workflow

* Update zooma-mappings-wf/Snakefile

Co-authored-by: Pablo Moreno <pcm32@users.noreply.github.com>

* replace conda-env with container for perl-atlas-modules

* remove --use-singularity

* try newer container

* tag: 0.3.0--h1b792b2_0

* tag: 0.2.0--h1b792b2_0

* add path to singularity software

* 0.3.1--pl5262h87f3376_2

* mv script to snakemake-codon-runs repo

* tag: 0.2.0--h1b792b2_0

* reinstate conda env for perl-atlas-modules

* remove `temp` definition of output files to avoid force-all in a second run of the workflow, and move temp files to log folder

* Fix path in lambda wildcards

* move .done files to log folder

* Fix input path in rule copy_reports_to_targetDir

* move logs out of ATLAS_EXPS

* fix IDF file path for proteomics

* Update Snakefile

* allow proteomics_baseline_dia experiments

* allow prot_baseline_dia for attempt_number > 1

* remove redundant dependency from conda env

* add def get_exp_type_from_xml(wildcards)

* Update Snakefile

* fix path for config xml file

* add prot_magetabfiles to config

* include mechanism to skip accessions for zooma mappings

* let user enable debugging for  condense_sdrf.pl

* do not ask for config xml in single-cell mode

* fix linting

* enable processing user-defined accessions

* move all logs and temp files to a dedicated log_path

* fix get_split_zooma_mapping_report_inputs

* attempt to avoid `Not all output, log and benchmark files of rule run_condense_sdrf contain the same wildcards`

* remove misleading wildcards

* remove misleading wildcards

* fix path

* fix 'Wildcards in input files cannot be determined from output files'

* fix 'Wildcards in input files cannot be determined from output files'

* fix linting errors

* fix syntax

* fix syntax

* fix linting

* remove f-string from log/inputs

* rm var logs_path from rules

* fix missing input for rule all

* rm global var logs_path

* use expand

* correct var name

* fix var name

* 'Wildcards' object has no attribute 'accession'

* sort wildcards in rule condensed_sdrf

* correct var name

* correct syntax

* use expand

* fix typo: accessions-> accession

* fix wd path

* define get_working_dir()

* mv code chunk

* use lambda wildcards in rule run_condense_sdrf

* use lambda wildcards in rule run_condense_sdrf

* add [:-1]

* provide a function that infers the appropriate prefix from the input or output

* Attempt to solve error: `Wildcards in input files cannot be determined from output files`

* attempt to solve 'TypeError: must be str or None, not set'

* apply snakefmt code formatter to rules/

* rm irrelevant comments

Co-authored-by: Iris Yu <irisyu@ebi.ac.uk>
Co-authored-by: Pablo Moreno <pcm32@users.noreply.github.com>